set number
set nowrap
set ic

colorscheme desert

" Disable the Arrow Keys for Movement
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>

" Ensure MySQL specific syntax highlighting
autocmd BufRead *.sql set filetype=mysql

" Open new window splits right and bottom
set splitbelow
set splitright

" Keep all swap files in separate directory
set directory=~/vim_swap_files/

" Enable Pathogen
execute pathogen#infect()
